### PR TITLE
How to accomplish a $this->getState() inside a Booking object?

### PR DESCRIPTION
**Pull request by gmorel**
Sorry, this is not really an issue.

Maybe this logic is thought to be always outside the Booking entity. But can you tell how to accomplish this without injecting to the Booking class the StateWorkflow object? I am refactoring a legacy code with states, and I had in mind to ask to the current state some features, example:

_Booking.php_

```
public function getMessage()
{
    return $this->getCurrentState()->getMessage();
}
```

I like that more than executing outside the class something like the following:
_SomeOther.php_

```
//stuff
$booking->getState($stateWorkflow)->getMessage();
```

### CODE REVIEW

**Comment by gmorel** [comment]
Sure, no problem.

The idea here is to lead States to be responsible for transitions.

You got a point. If you prefer following the [TellDontAsk](http://martinfowler.com/bliki/TellDontAsk.html) (if I follow you correctly?). 
You can put the transition entry point into [Booking::cancel(StateWorkflow $stateWorkflow)](https://github.com/gmorel/StateWorkflowDemo/blob/b3b48c0a291a9783435803341c8c14c7ac1d1f03/src/BookingEngine/Domain/Entity/Booking.php#L89-L100).

What about this ?

``` php
public function getMessage(StateWorkflow $stateWorkflow)
{
    return $this->getCurrentState($stateWorkflow)->getMessage();
}
```

I've modified [Booking](https://github.com/gmorel/StateWorkflowDemo/blob/b3b48c0a291a9783435803341c8c14c7ac1d1f03/src/BookingEngine/Domain/Entity/Booking.php#L89-L100) in order to show that. And added [Unit Test](https://github.com/gmorel/StateWorkflowDemo/blob/83f6458085f30c62879756a72ba77eaad89588e0/Test/BookingEngine/Domain/Entity/BookingTest.php#L20-L53) as example.
I let you review [my PR](https://github.com/gmorel/StateWorkflowDemo/pull/1/files). Hope it replies to your question.

Cheers

**Comment by hosseio** [comment]
You follow me right, yes.
The way you have done is what I am doing it too, but please let me go a little further: what if I need inside the Booking class ask for something? I like the idea of using the StateWorkflow for managing transitions, but what about only get information?
I just refactored that part in my class for doing it your way :) But this is something I have in my mind for a while.

Thanks!

**Comment by gmorel** [comment]
StateWorkflow was built with the idea in mind that [Booking](https://github.com/gmorel/StateWorkflowDemo/blob/master/src/BookingEngine/Domain/Entity/Booking.php) (Entity with State) is only knowing its current state. 

With that said. If you want to know more about other states:

Either you lead [Booking](https://github.com/gmorel/StateWorkflowDemo/blob/master/src/BookingEngine/Domain/Entity/Booking.php) to have the state you want and initiate a transition. (Not really what you want to do.)

Or you ask [StateWorkflow::getAvailableStates()](https://github.com/gmorel/StateWorkflowBundle/blob/master/StateEngine/StateWorkflow.php#L88)

Either ways you will need to inject [StateWorkflow](https://github.com/gmorel/StateWorkflowBundle/blob/master/StateEngine/StateWorkflow.php) unfortunately.

Did it help ? Or I miss something ?

**Comment by hosseio** [comment]
Id did help, thanks :) I am injecting StateWorkflow service when this is need it. This is resolved to me.

**Pull request merged**
